### PR TITLE
Local interface Module

### PR DESCRIPTION
**Pull request by raguay**
This module displays the IP address of the local interface. If clicked, it will open it in a web browser.

### CODE REVIEW

**Comment by raguay** [comment]
Sorry, I did not realize it. It's now removed.

**Comment by raguay** [comment]
Okay, it now gives and error condition to the exit code and shows a notification telling the interface isn't found and gives the suggestion of the first found interface for the system that isn't a loopback device. I think this is a much more robust version.

**Comment by emilylaguna** [comment]
Hi, @raguay Thanks for your contribution. I've added your module in, we'll be updating the website with the latest community modules soon: http://infinitydashboard.com/

**Comment by raguay** [comment]
Thanks. I like writing modules. It's really a lot of fun!

**Pull request merged**
